fix: centralizing w3 img in tablet view
scooby-doo-cade-voce/frontend pull request #40
Opened 2024-05-19 02:06 UTC by LanaGomes

Acertando responsividade imagem w3 do Hero para visão em Tablet.

2024-05-19 03:05 UTC, ylyra requested changes
Consegue remover o lg:items-center dessa mesma linha? Com o sm:items-center aplicado o lg:items-center não é necessário

2024-05-19 13:34 UTC, matteothebrave reviewed
@LanaGomes Assim que conseguir fazer as alterações, consigo aprovar e mergear

2024-05-19 14:19 UTC, rayane-barbosa commented
Acredito que o ideal seja alterar a disposição do texto e não da imagem conforme proposto no seu PR. Se desejar corrigir basta criar uma issue e seguir com a correção do texto conforme o layout do figma.
![image](https://github.com/scooby-doo-cade-voce/frontend/assets/82448039/0079c47f-78b1-4cdc-a301-4fcec83f82c1)

2024-05-23 04:01 UTC, JoaooowDev approved these changes

2024-05-24 14:20 UTC, JoaooowDev approved these changes

2024-05-24 14:20 UTC, merged