ci: criado workflow para executar eslint e codeQL em todos os PRs
scooby-doo-cade-voce/frontend pull request #66
Opened 2024-05-24 21:25 UTC by DanielRRocha

2024-05-24 22:31 UTC, ylyra requested changes
Acho que faz mais sentido deixar somente o codeQL, o ESLint é rodado toda vez que o cara faz um commit

2024-05-25 04:20 UTC, DanielRRocha commented
@ylyra no backend também roda no commit e mesmo assim rodou em um PR e pegou coisa errada. Rs

2024-05-25 11:16 UTC, ylyra commented
@DanielRRocha pelo que vi a do backend roda, mas não faz a fix dos erros, a do front faz.

2024-05-25 12:17 UTC, ylyra approved these changes

2024-05-25 12:17 UTC, merged